import os

TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_FROM = os.environ.get("TWILIO_WHATSAPP_FROM", "")
DRIVER_PHONE_NUMBER = os.environ.get("DRIVER_PHONE_NUMBER", "")
DEBUG = False
FILL_THRESHOLD = 80
COLLECTION_THRESHOLD = 70